[package]
name = "ling-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "ling"
path = "src/main.rs"

[dependencies]
blake3.workspace = true
ling-ast = { path = "../ling-ast" }
ling-diagnostics = { path = "../ling-diagnostics" }
ling-effects = { path = "../ling-effects" }
ling-eval = { path = "../ling-eval" }
ling-format = { path = "../ling-format" }
ling-hir = { path = "../ling-hir" }
ling-lsp = { path = "../ling-lsp" }
ling-project = { path = "../ling-project" }
ling-resolve = { path = "../ling-resolve" }
ling-semantic = { path = "../ling-semantic" }
ling-source = { path = "../ling-source" }
ling-syntax = { path = "../ling-syntax" }
ling-types = { path = "../ling-types" }
ling-unicode = { path = "../ling-unicode" }
rustyline.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde.workspace = true
toml.workspace = true

[lints]
workspace = true
