[package]
name = "ling-effects"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ling-diagnostics = { path = "../ling-diagnostics" }
ling-concurrency = { path = "../ling-concurrency" }
ling-hir = { path = "../ling-hir" }
ling-resolve = { path = "../ling-resolve" }
ling-source = { path = "../ling-source" }
ling-types = { path = "../ling-types" }
ling-unicode = { path = "../ling-unicode" }
unicode-normalization.workspace = true

[dev-dependencies]
ling-ast = { path = "../ling-ast" }
ling-syntax = { path = "../ling-syntax" }

[lints]
workspace = true
