[package]
name = "ling-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ling-cache = { path = "../ling-cache" }
ling-ast = { path = "../ling-ast" }
ling-effects = { path = "../ling-effects" }
ling-hir = { path = "../ling-hir" }
ling-project = { path = "../ling-project" }
ling-semantic = { path = "../ling-semantic" }
ling-resolve = { path = "../ling-resolve" }
ling-source = { path = "../ling-source" }
ling-syntax = { path = "../ling-syntax" }
ling-types = { path = "../ling-types" }
ling-unicode = { path = "../ling-unicode" }

[dev-dependencies]
ling-eval = { path = "../ling-eval" }
ling-format = { path = "../ling-format" }

[lints]
workspace = true
