[package]
name = "ling-lsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ling-diagnostics = { path = "../ling-diagnostics" }
ling-format = { path = "../ling-format" }
ling-source = { path = "../ling-source" }
ling-syntax = { path = "../ling-syntax" }
serde_json.workspace = true

[lints]
workspace = true
