[package]
name = "ling-format"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ling-diagnostics = { path = "../ling-diagnostics" }
ling-semantic = { path = "../ling-semantic" }
ling-source = { path = "../ling-source" }
ling-syntax = { path = "../ling-syntax" }
serde_json.workspace = true

[dev-dependencies]
ling-ast = { path = "../ling-ast" }
ling-effects = { path = "../ling-effects" }
ling-hir = { path = "../ling-hir" }
ling-resolve = { path = "../ling-resolve" }
ling-types = { path = "../ling-types" }

[lints]
workspace = true
